### PR TITLE
Allow `item` option to be a function

### PR DESCRIPTION
**Pull request by silverwind**
When creating a new list, it is useful to be able to add custom attributes and classes to list items during creation. This change allows `item` to be given as a function through which the user can return HTML based on each individual item's values.

### CODE REVIEW

**Comment by silverwind** [comment]
Found an issue: the function isnt called on `list.add`, looking into it.

**Comment by silverwind** [comment]
Another issue I plan to fix: List.js replaces the innerHTML of the matched class with the bare value, so for example when I want to wrap a value in a anchor tag:

````html
<li class="field"><a>value</a></li>
````

List.js replaces that with:

`````html
<li class="field">value</li>
````

I'll see to fixing that when `item` is a function.

**Comment by silverwind** [comment]
Okay, looks like everything is working after a rebase to master. Quick example that demonstrates what's possible with functions:

````html
<!DOCTYPE html><html><body>
<div id="users"><ul class="list"></ul></div>
<script src="dist/list.js"></script><script>

const list = new List('users', {
  item: function(values) {
    return `
      <li>
        <h3 class="name"><a href=".">${values.name}</a></h3>
        <p class="born born-${values.born}">In the year ${values.born}</p>
      </li>
    `;
  }
}, [
  {name: 'Jonny Strömberg', born: 1986},
  {name: 'Jonas Arnklint', born: 1985},
  {name: 'Martina Elm', born: 1986}
]);
list.add({name: 'Gustaf Lindqvist', born: 1983});

</script>
````

I also took the liberty to fix https://github.com/javve/list.js/issues/411 for the function case.

**Comment by sprain** [comment]
Would be great if the mehod was re-considered when updating list item values with `item.values{'name': 'John'}`.

**Comment by silverwind** [comment]
IIRC, I fixed that on my master branch in https://github.com/silverwind/list.js/commit/fc89a7e558ffbd7603015c68b25a03f04a49f790. Give it a try:

````
$ npm i https://github.com/silverwind/list.js/tarball/master
````

**Comment by javve** [comment]
Hey @silverwind! Sorry about the super slow response. I think this looks like a pretty cool feature. 

If you have continued with the development I would appreciate a new PR that not includes the `/dist` files and that includes a test or two (http:///overview/contribute/)  ❤️ 

I'll close the PR in the meantime.

**Pull request closed without merging**
