### PR TITLE
Add item template function

### PR DESCRIPTION
**Pull request by boidolr**
To further customize item creation it can be useful to have an actual function.
Regardless of whether you'd want to add this functionality the first four commits might be a nice refactoring for the structure of `templater`.

### CODE REVIEW

**Comment by javve** [comment]
This is a really nice feature @boidolr! Thank you so much and sorry for taking almost two years before I merged it 😳

**Comment by DavidBruchmann** [comment]
great, first time since two years I use it, and have to do directly an update 😂

**Comment by devgianlu** [comment]
I believe this broke `.values(newValues)`, see #698

**Comment by adriancb** [comment]
Further to @devgianlu's comment, I believe this regressed https://github.com/javve/list.js/issues/438

**Comment by Antonio-Bennett** [comment]
+1 ro @adriancb. This isn't gonna get fixed anytime soon :(

**Pull request merged**
