### PR TITLE
Update natural-sort.js

### PR DESCRIPTION
**Pull request by CBeloch**
fix javve/list.js#385

### CODE REVIEW

**Comment by chet** [comment]
Excited to see this pending, whatever it may end up looking like upon final commit. Also running into this bug. :)

**Comment by cscuderi** [comment]
This needs to get merged! :)

**Comment by agauniyal** [comment]
👍

**Comment by djbusby** [comment]
Also would like to see this merged

**Comment by javve** [comment]
Sorry for the slowness! It's now updated as of version v1.3.0 https://github.com/javve/list.js/tree/v1.3.0

**Comment by EugeneTM** [comment]
The problem is that the unicode comparison. We get divide by zero here.
```javascript
if (/[^\x00-\x80]/.test(oFxNcL + oFyNcL) && oFxNcL.localeCompare) {
                        var comp = oFxNcL.localeCompare(oFyNcL);
                        return comp / Math.abs(comp);
}
```

**Pull request closed without merging**
