### PR TITLE
multifilter functionality added

### PR DESCRIPTION
**Pull request by dagjomar**
I wanted to add multiple filters to the list, so this is how I added that functionality...

### CODE REVIEW

**Comment by ts** [comment]
Any chance this will get merged, perhaps into v1.2.0? I'm happy to help if that's all we're waiting for, @javve.

**Comment by mjoraid** [comment]
Just to help new comers, this what i did. Im sure someone can do better. 

From my class object, I made a few functions to use list.js library. Code samples like: 

```javascript
//this function will get the value from html dom when the user choose to filter a range 
LobbyClass.prototype.filterInt = function(dom_class, min, max)
{
    min = parseInt(min);
    max = parseInt(max);
  //this filter function will be store in array to be passed to list.js later on
    var filterFunction = function(item) {
        var intVal = parseInt(item.values()[dom_class]);
        if (intVal >= min && intVal <= max) {
            return true;
        } else {
            return false;
        }
    };

    this.addFilterAndApply(dom_class, filterFunction);//build up filters so we can have multiple filters     
};

LobbyClass.prototype.addFilterAndApply = function(type, filter)
{  //override previous function from same type, one filter for each type. 
    if (type && filter)
    {
        this.filters[type] = filter;
    }
    var allFilters = this.getFilters();
    if (allFilters.length > 0)
    {
        this.filterComp.filter(allFilters);//pass all filters to be applied.      
        this.checkTableRows();// to dsiplay message if no data found.
    }
};

LobbyClass.prototype.getFilters = function(name)
{
    if (name)
    {
        return this.filters[name];
    }
    else
    {
        //convert object to array
        var filters_arr = [];
        $.each(this.filters, function(index, data) {
            filters_arr.push(data);
        });
        return     filters_arr;
    }

};

**Comment by cbier** [comment]
+1! I manually merged this in and didn't see any conflicts. Not sure what that notification from GitHub means. Please merge this in!

**Comment by sandersu** [comment]
@cbier how and where did you merge this?

**Comment by BjoernHH** [comment]
The Code-Change in the first Posting has a small bug:
I use 2 filters
```
<div id="users">
  <input class="search" placeholder="name" />
  <input class="search" placeholder="born" />


  <div class="list">
    <div>
      <h3 class="name">Jonny Stromberg</h3>
      <p class="born">1986</p>
    </div>
    <div>
      <h3 class="name">Jonas Arnklint</h3>
      <p class="born">1985</p>
    </div>
    <div>
      <h3 class="name">Martina Elm</h3>
      <p class="born">1985</p>
    </div>
    <div>
      <h3 class="name">Gustaf Lindqvist</h3>
      <p class="born">1983</p>

    </div>
  </div>
</div>
<script src="js/list.js"></script>
<script>
var options = {
  valueNames: [ 'name', 'born' ]
};
var userList = new List('users', options);
</script>
```
If i write jo in the first field, filtering is ok (Jonny Stromberg, Jonas Arnklint).
If i than write 7 in the second field, filtering also ok (none)
But if i than delete the 7 from the second field, jo is still in the first field, filterig result is the full list, not Jonny Stromberg and Jonas Arnklint

**Comment by cbier** [comment]
@sandersu I manually added the changes to my local list.js

**Comment by lmartins** [comment]
Any chance this could be merged in the near future or should I look for alternatives?

**Pull request closed without merging**
