### PR TITLE
Debounced keyup handler in search

### PR DESCRIPTION
**Pull request by sheffieldnick**
As discussed in #621 this adds an optional debounced event handler in search & fuzzySearch. Setting the new options.searchDelay (default 0 ms) makes searching far more usable with very large lists and/or slow mobile devices.

Added documentation to List API describing the new option, suggesting setting it from 250-750 ms.

### CODE REVIEW

**Comment by SanmayJoshi** [comment]
Hi @sheffieldnick , I have forked this library and started a new project under the name of [invisearch.js](https://github.com/SanmayJoshi/invisearch.js) since this repo seemed a bit inactive. I would really love it if you could push this PR to [invisearch.js](https://github.com/SanmayJoshi/invisearch.js), and help me keep this awesome library updated. `/src` files haven't changed in the new project. Thanks

**Comment by sheffieldnick** [comment]
> Hi @sheffieldnick , I have forked this library and started a new project under the name of [invisearch.js](https://github.com/SanmayJoshi/invisearch.js) since this repo seemed a bit inactive. 

Surely better to talk to @javve with an offer to help maintain this project instead of just copying it and giving it a new name?

**Comment by SanmayJoshi** [comment]
> Surely better to talk to @javve with an offer to help maintain this project instead of just copying it and giving it a new name?

No doubt. Guess I was a bit too afraid to see this awesome library to be inactive. Am really looking forward for this library. What do you think @sheffieldnick should I do with the repo I have created? Deleting it seems proper.

**Comment by javve** [comment]
Hey @sheffieldnick, thanks a lot for your PRs and I'm so sorry for not reviewing them until now 😞 
I made a big update today. I updated all development dependencies and ran all code via Prettier, which feels great.

However, that also created a bunch of conflicts in your PRs. I'm not really sure why there is so many conflicts or why there is a bunch of random commits included. But I guess it would sort itself our if you could make it so that your PRs was up to date with the new master.

Could you do that? That would be fantastic!

**Comment by sheffieldnick** [comment]
> Could you do that? That would be fantastic!

No, but you've got all my code that had no conflicts at the time, so you are very welcome to do it yourself.

**Comment by javve** [comment]
That sounds reasonable @sheffieldnick 😅  Sorry for even asking you after all this time. I made it myself and put the fixes in this PR #696 

Super nice work! I really appreciate it even though I haven't worked with List.js for a few years now, I feel really bad for you and other people who've made PRs during this time. 

However, I hope to spend more time with this lib from now on!

**Pull request closed without merging**
