### PR TITLE
Bootstrap 4 compatible pagination

### PR DESCRIPTION
**Pull request by afermon**
Bootstrap 4 compatible pagination. Hope it help for a future release. Thanks!

https://v4-alpha.getbootstrap.com/components/pagination/

### CODE REVIEW

**Comment by Rainbowlemon** [comment]
Just looking around the docs to see the possibility to add custom classes to pagination existed, and came across this PR. This is a good start, but I reckon it'd be even more useful to be able to add custom classes/templates for ellipsis, selected and default pagination links via the pagination options.

**Comment by DaTebe** [comment]
Is it intended to continue here?

**Comment by jcugley** [comment]
@Rainbowlemon would love to see this implemented!

**Comment by javve** [comment]
There is another [PR](https://github.com/javve/list.js/pull/591) with a more general solution to this problem. I'll go with that one but thanks for your efforts!

**Pull request closed without merging**
