### PR TITLE
Custom pagination item capability

### PR DESCRIPTION
**Pull request by dbrw**
You can add pagination custom item with this PR.

### CODE REVIEW

**Comment by Jastrzebowski** [comment]
I've just needed it too and thought before writing code lets check if there are no PRs waiting ;) Would love to see it soon. Will solve usage with Bootstrap 4

**Comment by javve** [comment]
Sorry about the super slow reply! this looks like a great feature. ⭐️ 
However, I would love to have a test included in this PR as well to make sure that it works.

**Comment by dbrw** [comment]
More commits will follow.

**Comment by javve** [comment]
This is great! Thank you so much.

...and, heh, sorry about the suuuuper slow review and merge 😳

**Pull request merged**
